ui: mocha-bdd
scripts:
  - "node_modules/chai/chai.js"
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: opera
    version: latest
  - name: safari
    version: 7..latest
  - name: ie
    version: 8..latest
  - name: iphone
    version: latest
  - name: android
    version: 4.0..latest
